Webshop/Webshop/Pages/AddUser.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;


namespace Webshop.Pages
{
    public class AddUserModel : PageModel
    {



        [BindProperty]
        [Required]
        [Display(Name = "Gebruikersnaam")]
        public string? Gebruikersnaam { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Wachtwoord")]
        public string? Wachtwoord { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string? Email { get; set; }

        public void OnGet()
        {
            string username = HttpContext.Session.GetString("Username");
            if (username == null)
            {
                // Redirect to login page if the user is not logged in
                Response.Redirect("/Inlog");
            }

        }

            public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Connect to the database
            string Conn = "Data Source=DESKTOP-CI1RHCI;Initial Catalog=AppleStore;Integrated Security=true;TrustServerCertificate=true; User Id=Jeffrey;Password=Jeffrey";
            IDbConnection dbConnection = new SqlConnection(Conn);

            string query = "INSERT INTO users (username, password, email) VALUES (@username, @password, @email)";
            IDbCommand dbCommand = new SqlCommand();
            dbCommand.CommandText = query;
            dbCommand.Connection = dbConnection;
            dbConnection.Open();

            SqlParameter paramA = new SqlParameter();
            paramA.ParameterName = "@username";
            paramA.Value = Gebruikersnaam;
            dbCommand.Parameters.Add(paramA);

            SqlParameter paramN = new SqlParameter();
            paramN.ParameterName = "@password";
            paramN.Value = Wachtwoord;
            dbCommand.Parameters.Add(paramN);

            SqlParameter paramP = new SqlParameter();
            paramP.ParameterName = "@email";
            paramP.Value = Email;
            dbCommand.Parameters.Add(paramP);

            dbCommand.ExecuteNonQuery();
            dbConnection.Close();

            return RedirectToPage("/Beheer");
            
        }
    }
}

Webshop/Webshop/Pages/Beheer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;


namespace Webshop.Pages
{
    public class BeheerModel : PageModel
    {
        public List<string[]> product = new List<string[]>();

        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Inlog");
        }


        public void OnGet()
        {
            string? username = HttpContext.Session.GetString("Username");
            if (username == null)
            {
                // Redirect to login page if the user is not logged in
                Response.Redirect("/Inlog");
            }
            // Connect to the database
            string Conn = "Data Source=DESKTOP-CI1RHCI;Initial Catalog=AppleStore;Integrated Security=true;TrustServerCertificate=true; User Id=Jeffrey;Password=Jeffrey";
            IDbConnection dbConnection = new SqlConnection(Conn);

            string query = "SELECT * FROM producten";
            IDbCommand dbCommand = new SqlCommand();
            dbCommand.CommandText = query;
            dbCommand.Connection = dbConnection;
            dbConnection.Open();

            var reader = dbCommand.ExecuteReader();

            while (reader.Read())
            {
                string[] producten = new string[4];
                producten[0] = reader.GetInt32(0).ToString();
                producten[1] = reader.GetString(1);
                producten[2] = reader.GetInt32(2).ToString();
                producten[3] = reader.GetString(3);

                product.Add(producten);
            }
            dbConnection.Close();
        }
    }
}

Webshop/Webshop/Pages/BestelDetails.cshtml.cs
using System.Data;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;


namespace Webshop.Pages
{
	public class BestelDetailsModel : PageModel
    {
        public int BestelID { get; set; }
        public int ProductID { get; set; }
        public string? naam { get; set; }
        public int Aantal { get; set; }
        public int totaalprijs { get; set; }
        public string? afbeelding { get; set; }

        public List<BestelDetails> BestelDetails { get; set; }



        public void OnGet(int BestelID)
        {
            BestelDetails = new List<BestelDetails>();

            this.BestelID = BestelID;

            // Connect to the database
            string Conn = "Data Source=DESKTOP-CI1RHCI;Initial Catalog=AppleStore;Integrated Security=true;TrustServerCertificate=true; User Id=Jeffrey;Password=Jeffrey";
            IDbConnection dbConnection = new SqlConnection(Conn);

            string query = "SELECT * FROM VW_BestellingenDetails where bestelID = " + BestelID.ToString();
            IDbCommand dbCommand = new SqlCommand();
            dbCommand.CommandText = query;
            dbCommand.Connection = dbConnection;
            dbConnection.Open();


                using (var reader = dbCommand.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var producten = new BestelDetails
                        {
                            BestelID = reader.GetInt32(0),
                            ProductID = reader.GetInt32(1),
                            naam = reader.GetString(2),
                            Aantal = reader.GetInt32(3),
                            totaalprijs = reader.GetInt32(4),
                            afbeelding = reader.GetString(5)
                        };
                        BestelDetails.Add(producten);
                    }
                }
        }
    }

    public class BestelDetails
    {
        public int BestelID { get; set; }
        public int ProductID { get; set; }
        public string? naam { get; set; }
        public int Aantal { get; set; }
        public int totaalprijs { get; set; }
        public string? afbeelding { get; set; }

    }
}

Webshop/Webshop/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

using Microsoft.AspNetCore.Mvc;
using System.Data;
using Microsoft.Data.SqlClient;

namespace Webshop.Pages
{
    public class CartModel : PageModel
    {
        public List<CartItem> CartItems { get; set; }


        public class CartItem
        {
            public string Id { get; set; }
            public string Name { get; set; }
            public double Price { get; set; }
            public int Quantity { get; set; }
        }


        public void OnGet()
        {
            Dictionary<string, int> shoppingCart = HttpContext.Session.Get<Dictionary<string, int>>("ShoppingCart") ?? new Dictionary<string, int>();

            CartItems = new List<CartItem>();

            foreach (var item in shoppingCart)
            {
                string productId = item.Key;
                int quantity = item.Value;

                // Connect to the database
                string Conn = "Data Source=DESKTOP-CI1RHCI;Initial Catalog=AppleStore;Integrated Security=true;TrustServerCertificate=true; User Id=Jeffrey;Password=Jeffrey";
                IDbConnection dbConnection = new SqlConnection(Conn);

                IDbCommand dbCommand = new SqlCommand();
                dbCommand.Connection = dbConnection;
                dbConnection.Open();

                dbCommand.CommandText = $"SELECT * FROM producten WHERE id = @productId";

                SqlParameter paramA = new SqlParameter();
                paramA.ParameterName = "@productId";
                paramA.Value = productId;
                dbCommand.Parameters.Add(paramA);

                var reader = dbCommand.ExecuteReader();

                if (reader.Read())
                {
                    CartItems.Add(new CartItem
                    {
                        Id = reader.GetInt32(0).ToString(),
                        Name = reader.GetString(1),
                        Price = reader.GetInt32(2),
                        Quantity = quantity
                    });
                }

                dbConnection.Close();
            }
        }

        public IActionResult OnPostEmptyCart()
        {
            HttpContext.Session.Remove("ShoppingCart");
            return RedirectToPage("/Cart");
        }
    }
}

Webshop/Webshop/Pages/Dashboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Webshop.Pages
{
    public class DashboardModel : PageModel
    {
        public void OnGet()
        {
            string? username = HttpContext.Session.GetString("Username");
            if (username == null)
            {
                // Redirect to login page if the user is not logged in
                Response.Redirect("/Inlog");
            }
        }
    }
}

Webshop/Webshop/Pages/DashboardEdit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Webshop.Pages
{
    public class DashboardEditModel : PageModel
    {
        public void OnGet()
        {
            string? username = HttpContext.Session.GetString("Username");
            if (username == null)
            {
                // Redirect to login page if the user is not logged in
                Response.Redirect("/Inlog");
            }
        }
    }
}

Webshop/Webshop/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;

namespace Webshop.Pages
{
    public class DeleteModel : PageModel
    {
        public int Artikelnummer { get; set; }

        public async Task<IActionResult> OnGetAsync(int artikelnummer)
        {
            Artikelnummer = artikelnummer;
            // Connect to the database
            string Conn = "Data Source=DESKTOP-CI1RHCI;Initial Catalog=AppleStore;Integrated Security=true;TrustServerCertificate=true; User Id=Jeffrey;Password=Jeffrey";
            IDbConnection dbConnection = new SqlConnection(Conn);

            string query = "DELETE FROM producten WHERE ID = @artikelnummer";
            IDbCommand dbCommand = new SqlCommand();
            dbCommand.CommandText = query;
            dbCommand.Connection = dbConnection;
            dbConnection.Open();

            SqlParameter paramA = new SqlParameter();
            paramA.ParameterName = "@artikelnummer";
            paramA.Value = artikelnummer;
            dbCommand.Parameters.Add(paramA);

            dbCommand.ExecuteNonQuery();
            dbConnection.Close();

            return RedirectToPage("Beheer");
        }
    }
}

Webshop/Webshop/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using System.Text.Json;
using System.Data;
using Microsoft.Data.SqlClient;

namespace Webshop.Pages
{
    public class IndexModel : PageModel
    {
        public List<string[]> laptopss = new List<string[]>();


        public class CartModel
        {
            public string Id { get; set; }
            public string Name { get; set; }
            public double Price { get; set; }
            public int Quantity { get; set; }
        }

        public void OnGet(string filterOption, double? minPrice, double? maxPrice)
        {
            // Connect to the database
            string Conn = "Data Source=DESKTOP-CI1RHCI;Initial Catalog=AppleStore;Integrated Security=true;TrustServerCertificate=true; User Id=Jeffrey;Password=Jeffrey";

            IDbConnection dbConnection = new SqlConnection(Conn);

            IDbCommand dbCommand = new SqlCommand();
            dbCommand.Connection = dbConnection;
            dbConnection.Open();

            if (string.IsNullOrEmpty(filterOption))
            {
                dbCommand.CommandText = $"SELECT * FROM producten";
            }
            else
            {
                dbCommand.CommandText = $"SELECT * FROM producten WHERE naam LIKE '%{filterOption}%'";
            }
            if (minPrice.HasValue && maxPrice.HasValue)
            {
                dbCommand.CommandText += $" AND price BETWEEN {minPrice.Value} AND {maxPrice.Value}";
            }
            var reader = dbCommand.ExecuteReader();

            while (reader.Read())
            {
                string[] laptops = new string[4];
                laptops[0] = reader.GetInt32(0).ToString();
                laptops[1] = reader.GetString(1);
                laptops[2] = reader.GetInt32(2).ToString();
                laptops[3] = reader.GetString(3);

                laptopss.Add(laptops);
            }
            dbConnection.Close();

        }

        public void OnPostAddToCart(string id)
        {
            //Haalt de data uit de shopping cart session
            Dictionary<string, int> shoppingCart = HttpContext.Session.Get<Dictionary<string, int>>("ShoppingCart") ?? new Dictionary<string, int>();

            if (shoppingCart.ContainsKey(id))
            {
                shoppingCart[id] += 1; 
            }
            else
            {
                shoppingCart[id] = 1; 
            }

            //Slaat de dingetje op :)
            HttpContext.Session.Set("ShoppingCart", shoppingCart);

            Response.Redirect("/Index");
        }
    }

    public static class SessionExtensions
    {
        public static void Set<T>(this ISession session, string key, T value)
        {
            session.SetString(key, JsonSerializer.Serialize(value));
        }

        public static T Get<T>(this ISession session, string key)
        {
            var value = session.GetString(key);
            return value == null ? default(T) : JsonSerializer.Deserialize<T>(value);
        }
    }
}

Webshop/Webshop/Pages/UserManagement.cshtml.cs
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;


namespace Webshop.Pages
{
    public class UserManagementModel : PageModel
    {

        public class User
        {
            public int Id { get; set; }
            public string? Gebruikersnaam { get; set; }
            public string? Wachtwoord { get; set; }
            public string? Email { get; set; }
        }


        public List<User> Users { get; set; }



        public async Task OnGetAsync()
        {
            string? username = HttpContext.Session.GetString("Username");
            if (username == null)
            {
                // Redirect to login page if the user is not logged in
                Response.Redirect("/Inlog");
            }
            // Connect to the database
            string Conn = "Data Source=DESKTOP-CI1RHCI;Initial Catalog=AppleStore;Integrated Security=true;TrustServerCertificate=true; User Id=Jeffrey;Password=Jeffrey";
            IDbConnection dbConnection = new SqlConnection(Conn);

            string query = "SELECT * FROM users";
            IDbCommand dbCommand = new SqlCommand();
            dbCommand.CommandText = query;
            dbCommand.Connection = dbConnection;
            dbConnection.Open();

                var reader = dbCommand.ExecuteReader();

                Users = new List<User>();

                while (reader.Read())
                {
                    var user = new User
                    {
                        Id = reader.GetInt32(0),
                        Gebruikersnaam = reader.GetString(1),
                        Wachtwoord = reader.GetString(2),
                        Email = reader.GetString(3)
                    };

                    Users.Add(user);
                }
            dbConnection.Close();
        }


        public async Task<IActionResult> OnPostDeleteUserAsync(int id)
        {
            // Connect to the database
            string Conn = "Data Source=DESKTOP-CI1RHCI;Initial Catalog=AppleStore;Integrated Security=true;TrustServerCertificate=true; User Id=Jeffrey;Password=Jeffrey";
            IDbConnection dbConnection = new SqlConnection(Conn);

            string query = "DELETE FROM users WHERE id = @id";
            IDbCommand dbCommand = new SqlCommand();
            dbCommand.CommandText = query;
            dbCommand.Connection = dbConnection;
            dbConnection.Open();


            SqlParameter param = new SqlParameter();
            param.ParameterName = "@id";
            param.Value = id;
            dbCommand.Parameters.Add(param);

                dbCommand.ExecuteNonQuery();

                return RedirectToPage("/UserManagement");
            
        }
    }
}

Webshop/Webshop/Pages/Beheer.cshtml
@page
@model Webshop.Pages.BeheerModel
@{
    ViewData["Title"] = "Beheer Page";
}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.3.0/css/all.css">
<div class="container">
    <div class="row justify-content-between align-items-center py-4">
        <div class="col-md-12 text-right">
            <a href="/insert" class="btn btn-link text-dark mr-3"><i class="fas fa-plus"></i></a>
            <a href="/UserManagement" class="btn btn-link text-dark mr-3"><i class="fas fa-users"></i></a>
            <a href="/Dashboard" onclick="window.open('/Dashboard', 'popup', 'fullscreen=yes'); return false;" class="btn btn-link text-dark mr-3"><i class="fa-solid fa-chart-line"></i></a>
            <a href="/DashboardEdit" target="_blank" class="btn btn-link text-dark mr-3"><i class="fa-solid fa-file-pen"></i></a>
            <a href="/KlantenSysteem" class="btn btn-link text-dark mr-3"><i class="fas fa-address-book"></i></a>
            <a asp-page-handler="Logout" class="btn btn-link text-dark"><i class="fas fa-sign-out-alt"></i></a>
        </div>
    </div>
</div>


    <div class="table-responsive">
        <table class="table table-hover table-bordered mt-4">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Naam</th>
                    <th scope="col">Prijs</th>
                    <th scope="col">Afbeelding</th>
                    <th scope="col">Beheer</th>
                </tr>
            </thead>
            <tbody>
                @foreach (string[] shirt in Model.product)
                {
                    <tr>
                        <td>@shirt[1]</td>
                        <td>€@shirt[2]</td>
                        <td><img src='Images\@shirt[3]' class="img-fluid"></td>
                        <td>
                            <a href="/Update?artikelnummer=@shirt[0]" class="btn btn-primary btn-sm mr-2"><i class="fas fa-edit"></i> Bewerken</a>
                            <a href="/Delete?artikelnummer=@shirt[0]" class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i> Verwijderen</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

 <style>
.container {
  margin-top: 50px;
}

     .btn-primary {
         background-color: #F2F2F2;
         color: #333333;
         font-size: 20px;
         font-weight: 500;
         border: none;
         border-radius: 20px;
         padding: 10px 20px;
         margin-right: 10px;
     }

     .btn-danger {
         background-color: #F2F2F2;
         color: #333333;
         font-size: 20px;
         font-weight: 500;
         border: none;
         border-radius: 20px;
         padding: 10px 20px;
     }

         .btn-primary:hover,
         .btn-danger:hover {
             background-color: #E6E6E6;
             color: #333333;
             cursor: pointer;
         }


.table {
  font-size: 18px;
  font-weight: 400;
}

.table thead th {
  font-weight: 500;
}

.table-responsive {
  overflow-x: auto;
}

.table-bordered th,
.table-bordered td {
  border: 1px solid #dcdcdc;
}

.table td img {
  width: 150px;
  height: auto;
}




 </style>

Webshop/Webshop/Pages/Delete.cshtml
@page
@model Webshop.Pages.DeleteModel
@{
}

Webshop/Webshop/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@if (Request.Query["refresh"] == "true")
{
    <meta http-equiv="refresh" content="0">
}

<style>
    .icon-hover:hover {
        border-color: #3b71ca !important;
        background-color: white !important;
    }

        .icon-hover:hover i {
            color: #3b71ca !important;
        }
</style>

<section class="my-4">
    <div class="container">
        <div class="row">
            <!-- sidebar -->
            <div class="col-lg-3">
                <!-- Toggle button -->
                <button class="btn btn-outline-secondary mb-3 w-100 d-lg-none"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span>Show filter</span>
                </button>
                <!-- Collapsible wrapper -->
                <div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingTwo">
                            <button class="accordion-button text-dark bg-light"
                                    data-mdb-target="#panelsStayOpen-collapseTwo"
                                    aria-expanded="true"
                                    aria-controls="panelsStayOpen-collapseTwo">
                                Type
                            </button>
                        </h2>
                        <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse show" aria-labelledby="headingTwo">
                            <div class="accordion-body">
                                <div>
                                    <form method="get">
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="filterOption" value="" id="flexRadioDefault1" checked>
                                            <label class="form-check-label" for="flexRadioDefault1">
                                                All
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="filterOption" value="Macbook" id="flexRadioDefault2">
                                            <label class="form-check-label" for="flexRadioDefault2">
                                                Macbook
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="filterOption" value="Ipad" id="flexRadioDefault3">
                                            <label class="form-check-label" for="flexRadioDefault3">
                                                Ipad
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="filterOption" value="Iphone" id="flexRadioDefault4">
                                            <label class="form-check-label" for="flexRadioDefault4">
                                                Iphone
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="filterOption" value="Mac" id="flexRadioDefault5">
                                            <label class="form-check-label" for="flexRadioDefault5">
                                                Mac
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="filterOption" value="Airpods" id="flexRadioDefault6">
                                            <label class="form-check-label" for="flexRadioDefault6">
                                                Airpods
                                            </label>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Apply</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    @*<div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                            <button class="accordion-button text-dark bg-light"
                                    type="button"
                                    data-mdb-toggle="collapse"
                                    data-mdb-target="#panelsStayOpen-collapseThree"
                                    aria-expanded="false"
                                    aria-controls="panelsStayOpen-collapseThree">
                                Price
                            </button>
                        </h2>
                        <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse show" aria-labelledby="headingThree">
                            <div class="accordion-body">
                                <div class="range">
                                    <input type="range" class="form-range" id="customRange1" />
                                </div>
                                <div class="row mb-3">
                                    <div class="col-6">
                                        <p class="mb-0">Min</p>
                                        <div class="form-outline">
                                            <input type="number" id="minPrice" class="form-control" />
                                            <label class="form-label" for="minPrice">$0</label>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <p class="mb-0">Max</p>
                                        <div class="form-outline">
                                            <input type="number" id="maxPrice" class="form-control" />
                                            <label class="form-label" for="maxPrice">$100000</label>
                                        </div>
                                    </div>
                                </div>
                                <button type="button" class="btn btn-white w-100 border border-secondary" data-min-price="0" data-max-price="100000" onclick="filterByPrice()">Apply</button>
                            </div>
                        </div>
                    </div>*@


                </div>
            </div>
            <!-- sidebar -->
            <!-- products -->
            <div class="col-lg-9">
                <div class="row justify-content-start">
                    @foreach (string[] laptops in Model.laptopss)
                    {
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="card mb-4">
                                <img class="card-img-top" src="Images/@laptops[3]" alt="@laptops[1]" style="object-fit: cover; height: 180px; ">
                                <div class="card-body">
                                    <h5 class="card-title">@laptops[1]</h5>
                                    <p class="card-text">€@laptops[2]</p>
                                    <form asp-page-handler="AddToCart" method="post">
                                        <input type="hidden" name="id" value="@laptops[0]" />
                                        <button type="submit" class="btn btn-outline-primary">
                                            <i class="fas fa-cart-plus"></i> Add to Cart
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

            <!-- products -->
        </div>
    </div>




    <style>

        .col-lg-3 {
            flex: 0 0 25%;
            max-width: 25%;
        }

        .col-lg-9 {
            flex: 0 0 75%;
            max-width: 75%;
        }
    </style>

Webshop/Webshop/Pages/UserManagement.cshtml
@page
@model Webshop.Pages.UserManagementModel
@{
    ViewData["Title"] = "User Management";
}

<style>
    #fas fa-edit {
        width: 50px;
        font-size: 30px;
        color:red;
    }
    #fas fa-trash-alt {
        width: 50px;
        font-size: 30px;
        color:red;
    }
</style>

<div class="container mt-5">
    <h1 class="text-center mb-4">@ViewData["Title"]</h1>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Gebruikersnaam</th>
                        <th>Email</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.Users)
                    {
                        <tr>
                            <td>@user.Gebruikersnaam</td>
                            <td>@user.Email</td>
                            <td>
                                <button> <a asp-page="./EditUser" asp-route-id="@user.Id"><i class="fas fa-edit"></i></a> </button>
                                <form asp-page-handler="DeleteUser" method="post" onsubmit="return confirm('Weet je zeker dat je deze user wilt verwijderen?')">
                                    <input type="hidden" name="id" value="@user.Id" />
                                    <button type="submit"><i class="fas fa-trash-alt"></i></button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="text-center">
                <a asp-page="/AddUser" class="btn btn-primary">Voeg gebruiker toe</a>
                <a href="/Beheer" class="btn btn-primary">Terug</a>
            </div>
        </div>
    </div>
</div>